[package]
name = "k1"
edition = "2021"
version.workspace = true

[dependencies]
dirs.workspace = true
bincode.workspace = true
serde.workspace = true
serde_json.workspace = true
consensus-pow.workspace = true