[workspace]
resolver = "2"

members = [
    "x",
    "consensus/core",
    "consensus/pow",
    "api",
    "chain",
    "p2p",
    "rpc",
]

[workspace.dependencies]
crypto = "0.5.1"
digest = "0.10.7"
sha2 = "0.10.8"
serde = { version = "1.0.202", features = ["derive"] }
hex = "0.4.3"
serde_json = "1.0.117"
bincode = "1.3"
