[workspace]
resolver = "2"

#Members List
members = [
    "x",
    "consensus/core",
    "consensus/pow",
    "api",
    "p2p",
]

[workspace.package]
version = "0.2.0"

#Dependencies Workspace
[workspace.dependencies]
crypto = "0.5.1"
digest = "0.10.7"
sha2 = "0.10.8"
serde = { version = "1.0.202", features = ["derive"] }
hex = "0.4.3"
serde_json = "1.0.117"
bincode = "1.3"
jsonrpc-core = "18.0"
jsonrpc-http-server = "18.0"
futures = "0.3.30"
secp256k1 = { version = "0.29.0", features = ["rand"] }
rand = "0.8.5"
bip39 = { version = "2.0.0", features = ["rand"] }
colored = "2.0"
dirs = "5.0.1"
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros"] }


#Path List
x = { path = "x" }
consensus-core = { path = "consensus/core" }
consensus-pow  = { path = "consensus/pow" }
api = { path = "api" }
p2p = { path = "p2p" }