[package]
name = "simulation"
edition = "2021"
version.workspace = true

[dependencies]
dirs.workspace = true
bincode.workspace = true
serde.workspace = true
serde_json.workspace = true
consensus-pos.workspace = true