[package]
name = "consensus-pos"
version.workspace = true
license = "Apache-2.0"
edition = "2021"
publish = false


[dependencies]
blake3.workspace = true
hex.workspace = true
serde.workspace = true
bincode.workspace = true