[package]
name = "framework"
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true


[dependencies]
move-binary-format.workspace = true
move-core-types.workspace = true