[package]
name = "k2"
edition = "2021"
version.workspace = true

[dependencies]
dirs.workspace = true
bincode.workspace = true
serde.workspace = true
serde_json.workspace = true
consensus-pos.workspace = true
secp256k1.workspace = true
sha2.workspace = true
hex.workspace = true
log.workspace = true
move-vm-runtime.workspace = true
move-vm-types.workspace = true
move-core-types.workspace = true
move-stdlib.workspace = true
move-stdlib-natives.workspace = true