[package]
name = "kari-move"
edition = "2021"
version.workspace = true

[dependencies]
move-binary-format.workspace = true
move-cli.workspace = true
move-compiler.workspace = true
move-disassembler.workspace = true
move-ir-types.workspace = true
move-package.workspace = true
move-prover.workspace = true
move-unit-test.workspace = true

