name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'documentation/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/
            ~/.cargo/git/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install mdBook
        run: |
          if ! command -v mdbook &> /dev/null; then
            cargo install mdbook mdbook-linkcheck
          fi

      - name: Verify links
        run: |
          cd documentation/book
          mdbook test
        continue-on-error: true

      - name: Build Documentation
        run: |
          cd documentation/book
          mdbook build

      - name: Check build output
        run: |
          test -d documentation/book/book || exit 1
          test -f documentation/book/book/index.html || exit 1

      - name: Configure Jekyll
        run: |
          echo "theme: jekyll-theme-cayman" > documentation/book/book/_config.yml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/book/book
          publish_branch: gh-pages
          commit_message: "docs: update documentation site [skip ci]"
          enable_jekyll: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'