name: Deploy Documentation

on:
  push:
    branches: [main]
    paths: ['documentation/**']

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/
            target/
          key: ${{ runner.os }}-mdbook-${{ hashFiles('**/book.toml') }}

      - name: Install mdBook
        run: cargo install mdbook mdbook-linkcheck

      - name: Build docs
        run: |
          cd documentation/book
          mdbook build
          
      - name: Setup Jekyll
        run: |
          mkdir -p _site
          cp -r documentation/book/book/* _site/
          cat > _site/_config.yml <<EOL
          remote_theme: pages-themes/cayman@v0.2.0
          plugins:
          - jekyll-remote-theme
          title: Kanari SDK Documentation
          description: Documentation for the Kanari SDK
          EOL
          
          find _site -type f -name "*.html" -exec sh -c '
            tempfile=\$(mktemp)
            echo "---" > "\$tempfile"
            echo "layout: default" >> "\$tempfile"
            echo "---" >> "\$tempfile"
            cat "{}" >> "\$tempfile"
            mv "\$tempfile" "{}"
          ' \;

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

          