name: rust

on:
    push:
      branches: [ "main" ]
      tags: "v*"
    pull_request:
      branches: [ "main" ]
  
env:
    CARGO_TERM_COLOR: always
    MNEMONIC_LENGTH: 24  # Set fixed mnemonic length
    NETWORK_TYPE: devnet
    RPC_PORT: 3031
    NETWORK_DOMAIN: devnet.kari.network
  
permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v3
        
        - name: Install Rust toolchain
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            override: true

        - name: Cache dependencies
          uses: actions/cache@v2
          with:
            path: |
              ~/.cargo/registry
              ~/.cargo/git
              target
            key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

        - name: Build Release
          run: cargo build --release

        - name: Generate Wallet
          run: |
            echo "24" | cargo run --release --bin kari keytool generate
          
        - name: Run Kari Node
          run: |
            ./target/release/kari start \
                --network devnet \
                --rpc-port 3031 \
                --domain devnet.kari.network \
                 --headless