name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-gnu

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          curl \
          git-all \
          cmake \
          gcc \
          libssl-dev \
          pkg-config \
          libclang-dev \
          libpq-dev \
          build-essential \
          clang \
          llvm \
          make \
          tmux \
          xz-utils \
          ufw \
          gcc-mingw-w64-x86-64 \
          g++-mingw-w64-x86-64 \
          x86_64-linux-gnu-gcc
    - name: Install Rust toolchain
      run: rustup target add ${{ matrix.target }}
    - name: Build
      run: cargo build --target ${{ matrix.target }} --verbose