name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-gnu

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          curl \
          git-all \
          cmake \
          gcc \
          libssl-dev \
          pkg-config \
          libclang-dev \
          libpq-dev \
          build-essential \
          clang \
          llvm \
          make \
          tmux \
          xz-utils \
          ufw \
          gcc-mingw-w64-x86-64 \
          g++-mingw-w64-x86-64 \
          x86_64-linux-gnu-gcc

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        components: clippy, rustfmt
        override: true

    - name: Check formatting
      run: cargo fmt -- --check

    - name: Clippy
      run: cargo clippy --target ${{ matrix.target }} -- -D warnings

    - name: Build
      run: cargo build --target ${{ matrix.target }} --verbose

    - name: Run tests
      run: cargo test --target ${{ matrix.target }} --verbose

    - name: Generate coverage
      if: matrix.os == 'ubuntu-latest'
      run: |
        cargo install cargo-tarpaulin
        cargo tarpaulin --ignore-tests --target ${{ matrix.target }} --out Xml

    - name: Upload coverage
      if: matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v3